In [1]:
import tensorflow as tf


In [2]:
W = tf.Variable([3.], tf.float32)
b = tf.Variable([.3], tf.float32)
x = tf.placeholder(tf.float32)
y = W*x + b

In [6]:
init = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)
    print(sess.run(y, {x: [2, 3, 4]}))

[  6.30000019   9.30000019  12.30000019]


In [14]:
n_features = 2
n_labels = 3
weights = tf.Variable(tf.truncated_normal((n_features, n_labels)))
bias = tf.Variable(tf.zeros(n_labels))

init = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)
    output = sess.run([weights, bias])
    print(output)

[array([[ 0.21750078, -0.10462058, -1.44255912],
       [-1.45994651,  1.30047309,  0.85502207]], dtype=float32), array([ 0.,  0.,  0.], dtype=float32)]


In [22]:
x = tf.constant([1, 2, 3], shape=[3,1], dtype=tf.float32)
y_tilde = tf.matmul(weights ,x) + bias
with tf.Session() as sess:
    sess.run(init)
    print(sess.run(y_tilde))

[[-0.73748922 -0.73748922 -0.73748922]
 [-5.22213459 -5.22213459 -5.22213459]]


In [26]:
x = tf.placeholder(tf.float32)
y_tilde = tf.matmul(weights ,x) + bias
init = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)
    print(sess.run(y_tilde, {x: [[1.], [2.], [3.]]}))

[[ 1.48702848  1.48702848  1.48702848]
 [-0.66902423 -0.66902423 -0.66902423]]
